#!/bin/bash

# TODO: hardcoded path of home directory

LINEHASH="a7e9f1d3b4c8f2e0"
LINE='[ -f "${HOME}/.profiledir" ] && . "${HOME}/.profiledir"'
LINECMBN="\n${LINE} # ${LINEHASH}"
FILE="${HOME}/.profile"

grep -qF -- "${LINEHASH}" "${FILE}" || echo -e "${LINECMBN}" >> "${FILE}"
cp -f "./dropling/.profiledir" "${HOME}/.profiledir"
