#!/bin/bash

. ./app/config/app.conf

[ -d "${PROFILE_DIR}" ] ||
  mkdir -p "${PROFILE_DIR}"
ln -sf "${PWD}/app/profile" "${PROFILE_DIR}/${APP_NAME}.sh"

[ -d "${BIN_DIR}" ] ||
  mkdir -p "${BIN_DIR}"
ln -sf "${PWD}/app/bin/${APP_PREFIX}" "${BIN_DIR}/"

[ -d "${CONFIG_DIR}/${APP_NAME}" ] ||
  mkdir -p "${CONFIG_DIR}/${APP_NAME}"

for path in "${PWD}/app/config"/*.conf; do
  filename=$(basename "${path}")
  ln -sf "${path}" "${CONFIG_DIR}/${APP_NAME}/${filename}"
done
